CREATE DATABASE IF NOT EXISTS `job_portal`;
USE `job_portal`;

DROP TABLE IF EXISTS `job`;

CREATE TABLE `job` (
`id` BIGINT NOT NULL AUTO_INCREMENT,
`company` VARCHAR(255) DEFAULT NULL,
`description` VARCHAR(255) DEFAULT NULL,
`location` VARCHAR(255) DEFAULT NULL,
`title` VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
